### ISSUE TITLE
notes to address from running devtools::check()

### ISSUE THREAD

**Issue by ttimbers** [UBC-MDS/punisheR#38]
1. You should properly document this using Roxygen if you think users of your package might ever use these. If not, I might add "helper" to the filename and/or function names to make it clear users will not be using these.
```
checking for missing documentation entries ... WARNING
Undocumented code objects:
  ‘fit_and_score’ ‘fitter’ ‘forward_break_criteria’ ‘input_checks’
  ‘input_data_checks’ ‘parse_n_features’
All user-level objects in a package should have documentation entries.
See chapter ‘Writing R documentation files’ in the ‘Writing R
Extensions’ manual.
```

2. You can ignore the note below:
```
checking top-level files ... NOTE
Non-standard files/directories found at top level:
  ‘CONDUCT.md’ ‘CONTRIBUTING.md’
```

3. Take a look at these and fix any you think might be harmful
```
checking R code for possible problems ... NOTE
fit_and_score: warning in fitter(X = X_train_to_use, y = y_train):
  partial argument match of 'X' to 'X0'
fit_and_score: warning in fitter(X = X_train_to_use, y = y_train):
  partial argument match of 'y' to 'y0'
r_squared: no visible global function definition for ‘predict’
Undefined global functions or variables:
  predict
Consider adding
  importFrom("stats", "predict")
to your NAMESPACE file.
```

**Comment by topspinj** [comment]
I think you may be looking at another version of our code because these are issues that we have addressed earlier this week. 
```
‘fit_and_score’ ‘fitter’ ‘forward_break_criteria’ ‘input_checks’
  ‘input_data_checks’ ‘parse_n_features’
```
These functions do have documentation:
https://github.com/UBC-MDS/punisheR/blob/master/R/utils.R
https://github.com/UBC-MDS/punisheR/blob/master/R/checks.R

We changed our variable naming  'x0' and 'y0', so this error should now longer be appearing in the current version of our code:
https://github.com/UBC-MDS/punisheR/blob/master/R/utils.R#L45

**Comment by topspinj** [comment]
Resolved
